# Generated by Django 3.0.6 on 2020-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('_password', models.CharField(max_length=100)),
                ('sex', models.SmallIntegerField(choices=[('1', '男'), ('2', '女')], default=2)),
            ],
        ),
    ]
